language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t applikeme/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true applikeme/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-886075860709"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"